version: "3.7"

networks:
    back-end:
        driver: bridge

services:
    web:
        build:
            context: ./
            args:
                MINIO_ENDPOINT: "minio"
                MINIO_PORT: "9000"
                MINIO_SSL: "false"
                MINIO_ACCESS_KEY: "minio_user"
                MINIO_SECRET_KEY: "minio_password"
                PUBLIC_MAX_FILES: "10"
                PUBLIC_MAX_FILE_SIZE: "5242880"
                BODY_SIZE_LIMIT: "0"
        restart: always
        ports:
            - "5173:3000"
        depends_on:
            - postgres
            - minio
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
        command: /bin/sh -c "npx prisma migrate deploy && node index.js"
        networks:
            - back-end

    postgres:
        image: postgres:16.0-alpine3.18
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - back-end

    minio:
        image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
        command: minio server /data --console-address ":9090"
        restart: always
        environment:
            MINIO_ROOT_USER: "minio_user"
            MINIO_ROOT_PASSWORD: "minio_password"
        volumes:
            - minio-data:/data
        networks:
            - back-end

volumes:
    postgres-data:
    minio-data:
