version: "3.7"

services:
    postgres:
        image: postgres:16.0-alpine3.18
        restart: always
        ports:
            - "9191:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    minio:
        image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
        command: minio server /data --console-address ":9090"
        restart: always
        ports:
            - "9000:9000"
            - "9090:9090"
        environment:
            MINIO_ROOT_USER: "minio_user"
            MINIO_ROOT_PASSWORD: "minio_password"
        volumes:
            - minio-data:/data

volumes:
    postgres-data:
    minio-data:
