FROM node:18.16.1-alpine3.17 as build

ARG DATABASE_URL
ARG TELEGRAM_BOT_TOKEN
ARG ADMIN_ID
ARG MINIO_ENDPOINT
ARG MINIO_PORT
ARG MINIO_SSL
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY
ARG MAX_FILES

ENV DATABASE_URL=$DATABASE_URL
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ENV ADMIN_ID=$ADMIN_ID
ENV MINIO_ENDPOINT=$MINIO_ENDPOINT
ENV MINIO_PORT=$MINIO_PORT
ENV MINIO_SSL=$MINIO_SSL
ENV MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
ENV MINIO_SECRET_KEY=$MINIO_SECRET_KEY
ENV MAX_FILES=$MAX_FILES

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run check

ENV NODE_ENV=production

RUN npm run build

FROM node:18.16.1-alpine3.17 as prod

ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/build .

RUN npm install --omit=dev

EXPOSE 3000

CMD ["node", "index.js"]